sudo: false

language: r
pandoc_version: 2.10

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
  - Rscript -e "install.packages('devtools', repos='https://cran.rstudio.com')"
  - Rscript -e "devtools::install_github('rstudio/bookdown')"

script:
  - ./_build.sh
  - ./_deploy.sh
